### ISSUE TITLE
Couldn't create dataset 

### ISSUE THREAD

**Issue by vedal** [kanosawa/simple-face-alignment-pytorch#1]
Hi :)

I tried to follow your README to create a dataset according to 
`python make_300W_train_list.py ./datasets 300W_train.txt` 

but I get an error

```
Traceback (most recent call last):
  File "make_300W_train_list.py", line 79, in <module>
    make_300W_train_list(path_300W, box_datas, output_file_name)
  File "make_300W_train_list.py", line 65, in make_300W_train_list
    box_str = return_box(image_path, anno_path, box_data)
  File "make_300W_train_list.py", line 51, in return_box
    assert image_path in all_dict, '{} not find'.format(image_path)
AssertionError: datasets/ibug/image_092 _01 not find
```

any idea what the probelm could be?
I followed your instructions for folder tree closely, and the file is in the folder

**Comment by vedal** [comment]
found the error as a filename error in original dataset
